### ISSUE TITLE
不支持if？

### ISSUE THREAD

**Issue by mfkwvf** [niceue/tpl.js#5]
不支持if？

**Comment by niceue** [comment]
@mfkwvf 支持嵌入所有 js 语法

``` template
<# js 语句 #>
<#=变量#>
```

**Comment by mfkwvf** [comment]
问个多余的问题 http://validator.niceue.com/docs/common-rules.html 这个文档是系统生成的吗？如果是是什么系统？

**Comment by niceue** [comment]
用的博客系统 typecho，因为 markdown 和自带 markdown 评论的关系

**Comment by mfkwvf** [comment]
@niceue 喜欢你这个模版? 看过typecho源码，能共享不？邮箱mfkwvf@qq.com

**Comment by niceue** [comment]
@mfkwvf 制作的比较乱，没有形成一个主题，里面很多乱七八糟的文件和一些针对这个文档定制的东西。
你如果实在需要，我找时间整理一下给你

**Comment by mfkwvf** [comment]
@niceue 谢谢，有时间就塞一份给我，就免得去仿了。
